repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.18.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt --manifest-path riichienv/Cargo.toml --all -- --check
        language: system
        types: [rust]
        pass_filenames: false
      - id: clippy
        name: clippy
        entry: env PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1 cargo clippy --manifest-path riichienv/Cargo.toml --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
      - id: ruff-check
        name: ruff-check
        entry: uv run --directory riichienv ruff check . --fix
        language: system
        types: [python]
        pass_filenames: false
      - id: ty-check
        name: ty-check
        entry: uv run --directory riichienv ty check
        language: system
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: uv run --directory riichienv pytest
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff-format
        name: ruff-format
        entry: uv run --directory riichienv ruff format .
        language: system
        types: [python]
        pass_filenames: false

