name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  py-test:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run pytests
        run: uv run --python 3.14 pytest

  py-lint:
    name: ruff and ty
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run ruff format
        run: uv run --python 3.14 ruff format --check .

      - name: Run ruff check
        run: uv run --python 3.14 ruff check .

      - name: Run ty
        run: uv run --python 3.14 ty check

  rs-test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.87.0

      - name: Rust Cargo Test
        run: cargo test --all-targets --all-features

  rs-lint:
    name: rustfmt and clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.87.0
          components: rustfmt, clippy

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Rust Clippy
        run: PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1 cargo clippy --all-targets --all-features -- -D warnings

      - name: Rust Cargo Check
        run: cargo check --all-targets --all-features

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Install dependencies and Build
        run: |
          uv run --python 3.14 python -m riichienv.__init__ && echo OK
